# Configuration file for Hulk

# Limelight Configuration
limelight.camera0.name=limelight
limelight.camera1.name=camera_1
limelight.robot_to_camera0.x=12.375
limelight.robot_to_camera0.y=4.625
limelight.robot_to_camera0.z=6
limelight.robot_to_camera0.roll=-4.5
limelight.robot_to_camera0.pitch=-33.3
limelight.robot_to_camera0.yaw=3
limelight.max_ambiguity=0.3
limelight.max_z_error=0.75
limelight.linear_std_dev_baseline=0.02
limelight.angular_std_dev_baseline=0.06
limelight.camera0_std_dev_factor=1.0
limelight.camera1_std_dev_factor=1.0
limelight.linear_std_dev_megatag2_factor=0.5
limelight.angular_std_dev_megatag2_factor=Infinity

# Tuner Constants Configuration
# Steer Gains
tuner.steer_kp=100.0
tuner.steer_ki=0.0
tuner.steer_kd=0.5
tuner.steer_ks=0.1
tuner.steer_kv=1.59
tuner.steer_ka=0.0
# Drive Gains
tuner.drive_kp=0.8
tuner.drive_ki=0.0
tuner.drive_kd=0.0
tuner.drive_ks=0.0
tuner.drive_kv=0.124
# Other Values
tuner.slip_current=120.0
tuner.stator_current_limit=60.0
tuner.speed_at_12_volts=4.73
tuner.canbus_name=null
tuner.couple_ratio=3.5714285714285716
tuner.drive_gear_ratio=6.746031746031747
tuner.steer_gear_ratio=12.8
# wheel radius in inches
tuner.wheel_radius=2.0
tuner.pigeon_id=6

# Encoder Offsets (in rotations)
tuner.front_left_encoder_offset=0.178955078125
tuner.front_right_encoder_offset=0.211181640625
tuner.back_left_encoder_offset=0.16650390625
tuner.back_right_encoder_offset=-0.107177734375

# Motor IDs
tuner.front_left_drive_motor_id=21
tuner.front_left_steer_motor_id=20
tuner.front_left_encoder_id=2
tuner.front_right_drive_motor_id=23
tuner.front_right_steer_motor_id=22
tuner.front_right_encoder_id=3
tuner.back_left_drive_motor_id=27
tuner.back_left_steer_motor_id=26
tuner.back_left_encoder_id=5
tuner.back_right_drive_motor_id=25
tuner.back_right_steer_motor_id=24
tuner.back_right_encoder_id=4

# Inverted
tuner.front_left_steer_motor_inverted=false
tuner.front_left_steer_encoder_inverted=false
tuner.front_right_steer_motor_inverted=false
tuner.front_right_steer_encoder_inverted=false
tuner.back_left_steer_motor_inverted=false
tuner.back_left_steer_encoder_inverted=false
tuner.back_right_steer_motor_inverted=false
tuner.back_right_steer_encoder_inverted=false



# Module Positions (in inches)
tuner.front_left_x_pos=9.75
tuner.front_left_y_pos=9.75
tuner.front_right_x_pos=9.75
tuner.front_right_y_pos=-9.75
tuner.back_left_x_pos=-9.75
tuner.back_left_y_pos=9.75
tuner.back_right_x_pos=-9.75
tuner.back_right_y_pos=-9.75
